services:
  web:
    image: php:8.1-apache
    container_name: apache_server
    ports:
      - "8080:80" 
    volumes:
      - ./php/web:/var/www/html 
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    command: /bin/bash -c "apt-get update && apt-get install -y libpq-dev libzip-dev unzip && docker-php-ext-install pdo pdo_mysql && apache2-foreground"
    depends_on:
      - db 

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eshop_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # MinIO Console/API
      - "9001:9001" # MinIO Admin Console
    environment:
      MINIO_ROOT_USER: "admin"       # Set your MinIO access key
      MINIO_ROOT_PASSWORD: "admin"   # Set your MinIO secret key
    volumes:
      - minio-data:/data                      # Persistent storage for MinIO data
    command: server /data --console-address ":9001" # Enable Admin Console on port 9001

volumes:
  db_data:
  minio-data:

networks:
  app-network:
