SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `credit_cards`;
DROP TABLE IF EXISTS `comments`;
DROP TABLE IF EXISTS `products`;
DROP TABLE IF EXISTS `categories`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS `order_items`;


SET FOREIGN_KEY_CHECKS = 1;